### ISSUE TITLE
Specify a different edip

### ISSUE THREAD

**Issue by edgurgel** [asaaki/mix-edip#2]
I wonder if an option to override the edip repository would be accepted? I'm trying to find a potential bug in the building process but it's hard to use my fork as I would need to fork both projects.

Does this make sense?

**Comment by asaaki** [comment]
I guess you relate to asaaki/elixir-docker-image-packager#4?

I could implement such a thing, but would be more an undocumented thing, since this should not be the common use case. (thinking like _development/debug feature_)

**Comment by edgurgel** [comment]
Yeah, maybe it's not a desirable feature. Maybe just being able to use edip standalone would make the debugging process easier, but It's really complicated (to me) to move the `app` inside .edip folder as I have to exclude some stuff like `.git`, `.edip` itself (that recursion) and probably the trash that the CI already did.

Is there any reason why edip can't run "in place" ? I should probably move this issue to edip's repository...

**Comment by asaaki** [comment]
For debugging EDIP itself you could just checkout that repo and place your app in the root of it (this is what actually happens with this mix task: downloading EDIP, copying the app in it and running make).
With this approach you can at least test EDIP, but have no mix task for it.

I'm actually thinking about how to run EDIP _in place_, also about how to make the mix task more _standalone_ (via archive instead of project dependency, like phoenix does with its project generation task).

But bear with me, it will take some time, until I reach this point.

**Comment by edgurgel** [comment]
This makes sense. I will try this using it standalone! 

I agree that using a simple `mix install` would be nice to have, but I don't mind having it as a dependency for a specific environment like I do for `exrm` already

I will close this issue as it's no related any more from what I started :+1:
